/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.11 public/models/smiley/smile-round.gltf 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/smile-round.gltf')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.smile_high002_fora001.geometry} material={nodes.smile_high002_fora001.material} position={[3.226, -2.292, 0.688]} />
      <mesh geometry={nodes.smile_high002_fora.geometry} material={nodes.smile_high002_fora.material} position={[3.228, -2.29, 0]} rotation={[Math.PI / 2, 0, 0]} />
    </group>
  )
}

useGLTF.preload('/smile-round.gltf')
