/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.11 public/models/smiley/smile-separate.gltf 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/smile-separate.gltf')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.smile_high002_fora.geometry} material={materials.M1} position={[0.079, 1.307, 0]} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.smile_high002_fora001.geometry} material={materials.M1} position={[2.659, 4.585, 0]} />
      <mesh geometry={nodes.smile_high002_fora002.geometry} material={materials['M1.001']} position={[-2.475, 4.585, 0]} />
    </group>
  )
}

useGLTF.preload('/smile-separate.gltf')
