/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.10 public/models/scene.gltf 
Author: Rude Randal (https://sketchfab.com/Rude_Randal)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/smiling-ice-cream-d891f8d6e46848028219b81dc3d852f5
Title: Smiling Ice Cream
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Scene(props) {
  const { nodes, materials } = useGLTF('./models/scene.gltf')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={1.161}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group position={[-0.003, 1.246, 0.016]} rotation={[-2.999, 0.219, 0.071]} scale={0.667}>
            <mesh geometry={nodes.Object_26.geometry} material={materials.Sprikle_3} />
            <mesh geometry={nodes.Object_27.geometry} material={materials.Sprikle_1} />
            <mesh geometry={nodes.Object_28.geometry} material={materials.Sprikle_2} />
            <mesh geometry={nodes.Object_29.geometry} material={materials.Sprinkle_4} />
          </group>
          <mesh geometry={nodes.Object_4.geometry} material={materials.Cone} position={[0, 0.26, 0]} scale={0.367} />
          <mesh geometry={nodes.Object_6.geometry} material={materials.Bottom_IC} position={[0.001, 0.973, 0]} scale={0.456} />
          <mesh geometry={nodes.Object_8.geometry} material={materials.Top_IC} position={[-0.025, 1.396, 0]} rotation={[-0.036, 0.468, 0.08]} scale={0.356} />
          <mesh geometry={nodes.Object_10.geometry} material={materials.Cherry} position={[0.052, 1.763, -0.047]} rotation={[0, 0.186, -0.258]} scale={[0.107, 0.095, 0.107]} />
          <mesh geometry={nodes.Object_12.geometry} material={materials.Cherry_Top} position={[0.068, 1.827, -0.05]} rotation={[-3.042, -0.518, 0.293]} scale={[-0.005, 0.005, 0.005]} />
          <mesh geometry={nodes.Object_14.geometry} material={materials.Choco_Syurp} position={[-0.025, 1.396, 0]} rotation={[-0.036, 0.468, 0.08]} scale={0.364} />
          <mesh geometry={nodes.Object_16.geometry} material={materials.Eyes} position={[0.18, 0.628, 0.344]} rotation={[Math.PI / 2, 0, -0.404]} scale={0.07} />
          <mesh geometry={nodes.Object_18.geometry} material={materials.Eye_White} position={[0.18, 0.628, 0.345]} rotation={[Math.PI / 2, 0, -0.404]} scale={0.07} />
          <mesh geometry={nodes.Object_20.geometry} material={materials.Mouth} position={[0, -0.108, 0]} rotation={[Math.PI / 2, 0, 0]} scale={0.058} />
          <mesh geometry={nodes.Object_22.geometry} material={materials.Mouth_In} position={[0, 0.51, 0.001]} rotation={[Math.PI / 2, 0, 0]} scale={0.035} />
          <mesh geometry={nodes.Object_24.geometry} material={materials.Tongue} position={[0, 0.51, 0.004]} rotation={[Math.PI / 2, 0, 0]} scale={0.035} />
          <mesh geometry={nodes.Object_31.geometry} material={materials.Sprinkle_4} position={[-0.647, 0.598, -1.132]} rotation={[0.935, 0.674, 0.863]} scale={0.667} />
          <mesh geometry={nodes.Object_33.geometry} material={materials.Sprikle_3} position={[0.118, 1.41, -0.929]} rotation={[-0.669, 0.581, 0.051]} scale={0.667} />
          <mesh geometry={nodes.Object_35.geometry} material={materials.Sprinkle_4} position={[0.929, 1.191, -0.012]} rotation={[1.718, -0.78, -1.609]} scale={0.667} />
          <mesh geometry={nodes.Object_37.geometry} material={materials.Sprikle_2} position={[1.061, 0.443, 0.563]} rotation={[1.03, -0.233, -1.486]} scale={0.667} />
          <mesh geometry={nodes.Object_39.geometry} material={materials.Sprikle_3} position={[-0.866, 1.448, 0.655]} rotation={[-0.489, -0.389, -2.06]} scale={0.667} />
          <mesh geometry={nodes.Object_41.geometry} material={materials.Sprikle_1} position={[-0.859, 0.292, -0.515]} rotation={[2.588, -1.135, -1.603]} scale={0.667} />
          <mesh geometry={nodes.Object_43.geometry} material={materials.Sprikle_1} position={[0.832, 0.795, -0.611]} rotation={[0.636, 1.275, -0.917]} scale={0.667} />
          <mesh geometry={nodes.Object_45.geometry} material={materials.Sprikle_3} position={[0.747, 1.651, 0.997]} rotation={[2.639, 0.013, -0.628]} scale={0.667} />
          <mesh geometry={nodes.Object_47.geometry} material={materials.Sprikle_1} position={[-0.643, 0.656, 1.123]} rotation={[2.542, -0.281, -0.472]} scale={0.667} />
          <mesh geometry={nodes.Object_49.geometry} material={materials.Sprikle_3} position={[1.382, 0.892, 0.011]} rotation={[-0.259, -0.491, -1.374]} scale={0.667} />
          <mesh geometry={nodes.Object_51.geometry} material={materials.Sprikle_2} position={[-1.256, 0.945, 0.107]} rotation={[2.697, 1.191, -0.52]} scale={0.667} />
          <mesh geometry={nodes.Object_53.geometry} material={materials.Sprikle_1} position={[-1.256, 1.678, -0.355]} rotation={[1.422, 0.113, 1.097]} scale={0.667} />
          <mesh geometry={nodes.Object_55.geometry} material={materials.Sprinkle_4} position={[0.248, 0.603, 1.097]} rotation={[2.083, -0.339, 1.728]} scale={0.667} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('./models/scene.gltf')
